### PR TITLE
Updated descriptions of metrics to be self-explanatory

### PR DESCRIPTION
**Pull request by 33Fraise33**

### CODE REVIEW

**Comment by bluecmd** [comment]
Happy to merge, but not sure about the go.sum/go.mod files

**Comment by 33Fraise33** [comment]
Hello,

I am not a go programmer, but the project was not running unless I did: go mod tidy
That changed the files like you see here

**Comment by bluecmd** [comment]
> Hello,
> 
> I am not a go programmer, but the project was not running unless I did: go mod tidy That changed the files like you see here

My bad, seems the dependency bot messed stuff up. I have updated those files in master now, so if you rebase those changes should go away.

The tests are failing, fix those and we should be good to merge.

**Comment by 33Fraise33** [comment]
> > Hello,
> > I am not a go programmer, but the project was not running unless I did: go mod tidy That changed the files like you see here
> 
> My bad, seems the dependency bot messed stuff up. I have updated those files in master now, so if you rebase those changes should go away.
> 
> The tests are failing, fix those and we should be good to merge.

Fixed

**Comment by 33Fraise33** [comment]
> > Hello,
> > I am not a go programmer, but the project was not running unless I did: go mod tidy That changed the files like you see here
> 
> My bad, seems the dependency bot messed stuff up. I have updated those files in master now, so if you rebase those changes should go away.
> 
> The tests are failing, fix those and we should be good to merge.

This has been fixed by rebasing

**Review by bluecmd — APPROVED** [review]

**Comment by bluecmd** [comment]
@33Fraise33 Tests need updating as well

**Comment by 33Fraise33** [comment]
Tests are working on my system now

**Review by bluecmd — APPROVED** [review]

**Comment by bluecmd** [comment]
Thanks!

**Pull request merged**
