### PR TITLE
fix(CI): Add GitHub environment

### PR DESCRIPTION
**Pull request by bluecmd**
This might help #67 - but the documentation is not clear.

### CODE REVIEW

**Comment by bluecmd** [comment]
I added a GH_TOKEN secret but it still does not seem to work. This is how the secret page looks like:

image

It seems the Environment stuff is pretty new? And to activate it for an action it seems that we need to do something like this.

This is what the environment says:

image

**Comment by secustor** [comment]
Strange. The environment variable get set here  https://github.com/bluecmd/fortigate_exporter/blob/9c18f19e953a37e3653c47911ea46b7cfe7806ec/.github/workflows/release.yml#L57

This seems correct based on this documentation: https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow and this blog https://www.asyncapi.com/blog/automated-releases-part-two

**Comment by secustor** [comment]
Plugin docs: https://github.com/semantic-release/github#github-authentication

**Comment by bluecmd** [comment]
image

This seems to be a better configuration, now things seem to work as far as the secret goes. Still no binaries though, but this PR is not needed.

**Pull request closed without merging**
