### PR TITLE
doc: instructions for usage of CI

### PR DESCRIPTION
**Pull request by bluecmd**
Add instructions how to get started using the automatic builds.

Ping #38

### CODE REVIEW

**Review by secustor — COMMENTED** [review]
Is it intended that the build is run for all branches?    

I have never used quay.io for building.  What happens if the unit tests are failing?      
They are probably build anyway right?

**Comment by bluecmd** [comment]
> Is it intended that the build is run for all branches?
> 
> I have never used quay.io for building. What happens if the unit tests are failing?
> They are probably build anyway right?

We can disable all branches if you want - I think it should only build for the branches we have in the repository, which only we and Renovate can create.

My thinking was that if we enable building on all branches, it would be easy for people to try out some pending PR we have as there are images built for those. :latest is definitely going to be very confusing to use, so I guess people would have to use :master explicitly.

**Review by secustor — APPROVED** [review]
Some of the build jobs have failed. Is there a possibility to restart them?

**Comment by bluecmd** [comment]
Seems we ran out of build quota, so I changed it to only build the master branch for now.

**Pull request merged**
