### PR TITLE
feat: Add support for managed switches

### PR DESCRIPTION
**Pull request by thenodon**

### CODE REVIEW

**Comment by thenodon** [comment]
This PR replace the managed switch part of PR #206

**Review by bluecmd — APPROVED** [review]
Looks good to me, do you want the metrics to be named `..._bcast_` or do you prefer the more readable `..._broadcast_` et.al.?

**Comment by thenodon** [comment]
I have tried to stay as close to the attribute naming used in the fortigate api response and I think the short naming is used. I'm fine with both bcast and broadcast. I think you need to make the decision what is most inline with naming convention used in the the rest of the exporter.

**Comment by thenodon** [comment]
@bluecmd I'm not able to find any error running go fmt. Can you share what you see is failing and the check you run.

**Comment by thenodon** [comment]
Sorry was on the wrong go version. Hope it works now.

**Comment by bluecmd** [comment]
Thanks!

**Comment by thenodon** [comment]
Thank you - now time for the next PR :)

**Pull request merged**
