### PR TITLE
feat(flag): Valid default for auth-file

### PR DESCRIPTION
**Pull request by bluecmd**
Use the basename of the configuration file we use by default in the Docker image.

This avoids this non-helpful error message when running without arguments:
```
[debian]$ ./fortigate-exporter.linux.amd64
2021/07/10 21:45:43 FortigateExporter 1.5.1-1-g9994480 ( 9994480 )
2021/07/10 21:45:43 Failed to read API authentication map file: open : no such file or directory
```

### CODE REVIEW

**Review by secustor — CHANGES_REQUESTED** [review]
This change should be also reflected in the `Readme.md`. 

Also this commit type should be `feat`

**Comment by bluecmd** [comment]
> Also this commit type should be feat

I don't agree, but I will change it. My argument is that this doesn't change anything anyone could reasonably depend on (the default value right now is invalid and only causes crashes).

**Comment by secustor** [comment]
I agree with you, if somebody could depend on it, it should be a breaking change. 
But `minor` will not generate a release and as I understand you that is your intend.

**Review by secustor — APPROVED** [review]

**Comment by bluecmd** [comment]
Ah, right. You are correct :-)

**Comment by bluecmd** [comment]
What about `fix(flag)` instead? It feels a bit too much to bump to `1.8.0` just because of this.

**Pull request merged**
